# Generated by Django 4.1.5 on 2023-02-20 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0002_alter_fileupload_created_by_and_more'),
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='image',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='commons.fileupload'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='link',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
