# Generated by Django 4.1.5 on 2023-02-21 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='type',
        ),
    ]
