# Generated by Django 4.1.5 on 2023-02-21 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_remove_skill_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
