# Generated by Django 4.1.5 on 2023-03-09 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_education_title_experience_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='still_studying',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='experience',
            name='still_working',
            field=models.BooleanField(default=False),
        ),
    ]
