# Generated by Django 4.1.5 on 2023-02-20 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userinfo_main_image_userabout_socialmedia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialmedia',
            name='user_info',
        ),
    ]
