# Generated by Django 4.1.5 on 2023-02-20 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_whatidoitem_whatido'),
    ]

    operations = [
        migrations.RenameField(
            model_name='whatido',
            old_name='what_i_desc',
            new_name='what_i_do_desc',
        ),
    ]
