# Generated by Django 4.1.5 on 2023-03-01 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knox', '0008_remove_authtoken_salt'),
        ('user', '0007_alter_userinfo_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnoxAuthToken',
            fields=[
                ('authtoken_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='knox.authtoken')),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('detail', models.JSONField(blank=True, null=True)),
            ],
            bases=('knox.authtoken',),
        ),
    ]
